### ISSUE TITLE
cp-p not working the latest version of lf (r24)

### ISSUE THREAD

**Issue by AhmedHalim96** [Naheel-Azawy/cp_p#2]
So this is the line that I have in lfrc
`cmd paste $cp-p --lf-paste $id
`
when I try to paste something it gives me this error in my terminal:
`sh: 1: --new-line: not found`

**Comment by Dimfred** [comment]
Same here

**Comment by AhmedHalim96** [comment]
I have forked the repo and fixed the problem
closing this issue
