### ISSUE TITLE
Strace no longer shows write calls

### ISSUE THREAD

**Issue by Naheel-Azawy** [Naheel-Azawy/cp_p#4]
Not sure why, but I suspect something has changed in the coreutils?
Might check it out later

**Comment by lahwaacz** [comment]
You need to trace also the [copy_file_range](https://man7.org/linux/man-pages/man2/copy_file_range.2.html) system call, see https://github.com/coreutils/coreutils/blob/854e0351216869b8e79391e08b156127d1508beb/NEWS#L242-L244

**Comment by Naheel-Azawy** [comment]
Hi, I apologize for my overly slow response.
Thank you for finding out about the `copy_file_range` change. This clarifies the reason of that issue.
I tried adding it to `strace` but it seems that `copy_file_range` is not being called very frequently. This makes sense as it should replace the userspace `read` `write` approach. But that seems to ruin who idea of tracing.

```
$ dd status=progress bs=1M count=4096 if=/dev/zero of=./nothing
$ strace -q -e copy_file_range cp nothing nothing1
copy_file_range(3, NULL, 4, NULL, 9223372035781033984, 0) = 2147479552
copy_file_range(3, NULL, 4, NULL, 9223372035781033984, 0) = 2147479552
copy_file_range(3, NULL, 4, NULL, 9223372035781033984, 0) = 8192
copy_file_range(3, NULL, 4, NULL, 9223372035781033984, 0) = 0
+++ exited with 0 +++
```

As a side note, I checked `busybox`'s `cp` and it seems that they're using `sendfile`. stracing that call did a not bad job here.
But, I don't think it's sane to add busybox as a dependency. There's also a noticeable performance difference. And maybe busybox will move to `copy_file_range` later anyway.

Any suggestions?

**Comment by lahwaacz** [comment]
It doesn't ruin the idea for recursive copies of dirs with many small files. Obviously the output frequency depends on how big each file is and how fast the disks or network are, but I guess that's the best we can do.

**Comment by Naheel-Azawy** [comment]
You're right I guess. Better than nothing.
I like that you have refucktored the code. This little script is kind of too messed up and needs serious attention. I'm not I huge fan of bashism though. A rewrite should probably be considered by me some time later.
I'm still not happy with it but I'll close this issue as I doubt we can do any better for now.
